version: '3'
services:
  postgres:
    image: 'postgres:10.1'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lock

volumes:
  data:
    driver: local